#!/usr/bin/env python3
"""Generate the pinned Mozilla CA bundle C source."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


EXPECTED_SHA256 = "f66dff1bdf8f96060b8177976f8b7d9254bc89bc4db933d769f7384d28480bc9"
EXPECTED_CERTIFICATES = 121
SOURCE_DATE = "2026-08-13"
SOURCE_URL = f"https://curl.se/ca/cacert-{SOURCE_DATE}.pem"


def render(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    payload = "\n".join(rows)
    return f"""// SPDX-License-Identifier: MPL-2.0
// Generated by tools/dev/generate_ca_bundle.py; do not edit.
// Source: {SOURCE_URL}
// SHA-256: {EXPECTED_SHA256}

#include "wc/wc_ca_bundle.h"

#ifdef WHOIS_TLS
const unsigned char wc_ca_bundle_pem[] = {{
{payload}
}};
const size_t wc_ca_bundle_pem_len = sizeof(wc_ca_bundle_pem);
#else
const unsigned char wc_ca_bundle_pem[] = {{0}};
const size_t wc_ca_bundle_pem_len = 0;
#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    data = args.input.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(f"CA bundle SHA-256 mismatch: expected {EXPECTED_SHA256}, got {digest}")
    certificate_count = data.count(b"-----BEGIN CERTIFICATE-----")
    if certificate_count != EXPECTED_CERTIFICATES:
        raise SystemExit(
            f"CA bundle certificate count mismatch: expected {EXPECTED_CERTIFICATES}, got {certificate_count}"
        )

    output = render(data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(
        f"generated={args.output} sha256={digest} certificates={certificate_count} bytes={len(data)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())